### ISSUE TITLE
Build failure with RN 0.75.4

### ISSUE THREAD

**Issue by ashwini-ksingh** [HwangTaehyun/react-native-lottie-splash-screen#101]
```
RCT-Folly\/folly.framework\/Headers\/folly\/portability\/Config.h:20:10: note: did not find header 'folly-config.h' in framework 'folly'

react-native-lottie-splash-screen\/react_native_lottie_splash_screen.framework\/Headers\/RNSplashScreen.h:11:9: error: could not build module 'React'\n#import <React\/RCTBridgeModule.h>
<unknown>:0: error: failed to emit precompiled header
```

Getting this error after upgrading to 0.75.4. Working fine if I `remove react-native-lottie-splash-screen@1.1.2`
